name: fyp2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  firebase_auth: ^4.17.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^5.4.4
  audioplayers: 5.2.0
  shared_preferences: ^2.2.1
  intl: ^0.20.2
  fl_chart: 0.63.0
  http: ^1.1.0
  file_picker: ^8.0.7
  firebase_storage: ^11.7.7
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4
  video_player: ^2.7.2
  youtube_player_iframe: ^4.0.0
  uuid: ^4.2.2
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  timeago: ^3.6.0
  flutter_card_swiper: ^6.0.0
  flutter_cache_manager: ^3.3.1
  flutter_tts: ^3.8.5
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/rainbow.png
    - assets/logo.png
    - assets/bg_music.mp3
    - assets/click.mp3
    - assets/google_logo.png
    - assets/sounds/click.mp3
    - assets/sounds/success.mp3
    - assets/flashcards/
    - assets/flashcards/malay/
    - assets/sounds/error.mp3
    - assets/sounds/completion.mp3
    - assets/sounds/page_turn.mp3
    